### ISSUE TITLE
Use league/oauth2-client ~1.0@dev 

### ISSUE THREAD

**Issue by ctrlaltdylan** [rtheunissen/oauth2-reddit#4]
The other php league oauth2 clients have move onto using ~1.0@dev as a dependency. Unable to update the other oauth2 clients because this client uses league/oauth2-client : 1.12.

**Comment by rtheunissen** [comment]
:+1:  I'll take care of it asap.

**Comment by rtheunissen** [comment]
2.0.x-dev is now and will be kept up to date with ~1.0@dev of league/oauth2-client.

**Comment by ctrlaltdylan** [comment]
Wasn't able to pull the 2.0.x-dev branch even with minimum-stability set to dev but I was able to use your latest 1.\* release with OAuth 1.0.*@dev. Thank you!
