### ISSUE TITLE
authorization_code -> invalid grant

### ISSUE THREAD

**Issue by philippzentner** [rtheunissen/oauth2-reddit#6]
Hey!

I tried to follow your authorization code grant like documented.
But i get "invalid grant".

Best
Philipp

**Comment by rtheunissen** [comment]
@philippzentner Did you manage to get this working? What was the issue in the end?

**Comment by philippzentner** [comment]
I thought the request to reddit hasn't been made already but it was. So it was already used without me knowing about it and therefore invalid. I just had to get a new code&state.
